### PR TITLE
Add updater script and fingerprint for Prometheus

### PR DESCRIPTION
**Pull request by fmunozs**
This adds the fingerprint and updater script for Prometheus #295

### CODE REVIEW

**Comment by tooryx** [comment]
I just tested the plugin that seems to work fine. I would recommend adding a few information to the readme though:

- At least one public repository must exist;
- This repository must already contain some files (must not be uninitialized);
- The repository must have a default branch configured.

_~tooryx_

**Comment by fmunozs** [comment]
@tooryx hello, I've just updated the branch with changes from master. Is it OK?

**Comment by tooryx** [comment]
Yes, thank you.

_~tooryx_

**Review by tooryx — APPROVED** [review]

**Comment by fmunozs** [comment]
@tooryx seems like an internal check failed, is ther anything I can do to review/fix it?

**Comment by tooryx** [comment]
Hi @fmunozs,

No. At this stage no action is required from you, thank you.

_~tooryx_

**Pull request merged**
