### PR TITLE
add Gradio fingerprint (AI PRP: Request New Web Fingerprint for Gradio)

### PR DESCRIPTION
**Pull request by inkz**
issue: https://github.com/google/tsunami-security-scanner-plugins/issues/411

### CODE REVIEW

**Comment by leonardo-doyensec** [comment]
Hi @inkz.
Thank you for your contribution. I've noticed that since your initial commit more versions of Gradio have been released. Since it's important to have things up to date can you please add those? Specifically i'm talking about version `4.31.2` to `4.36.1`

Feel free to reach out.
~ Leonardo (Doyensec)

**Comment by inkz** [comment]
Hey @leonardo-doyensec, I added versions `4.31.2` - `4.36.1`.
Looks like new versions pop up quite frequently: https://pypi.org/project/gradio/#history

**Comment by leonardo-doyensec** [comment]
**LGTM** - Approved
@maoning you can merge it.

Reviewer: Leonardo, Doyensec

Plugin: Gradio Fingerprints
Feedback: Besides the version.txt file being initially incomplete, due to time delays, the script worked first try and the quality is good.
Drawbacks: None

**Comment by tooryx** [comment]
Hi @inkz,

Sorry for the delay. I am working on getting this merged. It should happen in the next following business days.

_~tooryx_

**Pull request merged**
