### PR TITLE
Fingerprint, Updater script for flyte console.

### PR DESCRIPTION
**Pull request by mr-mosi**
Hi dear tsunami team,

Regarding to issue #426

Please note that, Flyte project has various products but all of them use [flyteconsole](https://github.com/flyteorg/flyteconsole) as their dashboard. So as we need web fingerprints of this projects I run flyteconsole to get fingerprints. I used released versions because they were the most downloaded. and there is one or two versions which the release version not identical with git version, so they were ignored.

bests.

### CODE REVIEW

**Comment by lokiuox** [comment]
Hi @mr-mosi, thank you for your contribution!

I'm reviewing your plugin, but I noticed that the `versions.txt` file you supplied only contains 5 versions, up to `v1.1.3`, which is a release from June 2022.  From the GitHub repo and the container registry you're using in your script I can see there are way more releases, and the last tagged docker image is `v1.12.0`. Is there a reason why all these versions are missing?

As a general rule, the plugin should be able to fingerprint as many versions as possible, especially the latest versions.

**Review by lokiuox — APPROVED** [review]
**LGTM - Approved**
@maoning you can merge it.

_Reviewer_: Savio, Doyensec

_Plugin_: Flyte Console Fingerprints
_Feedback_: Besides the `version.txt` file being initially incomplete, the script worked first try and the quality is good. 
_Drawbacks_: None

**Comment by tooryx** [comment]
Hi @mr-mosi,

Please feel in the [participation form](https://bughunters.google.com/report/tsunami) and let me know when you did so.

_~tooryx_

**Comment by tooryx** [comment]
Hi @mr-mosi,

You did not let me know when you submitted the form. We updated the status, you should receive information soon.

_~tooryx_

**Pull request merged**
