### PR TITLE
Update binproto for adminer

### PR DESCRIPTION
**Pull request by fmunozs**
Hello, 

This PR is related to https://github.com/google/tsunami-security-scanner-plugins/issues/274 

Adds support for Adminer 4.8.1, 4.8.0 and 4.7.9. 
Adds update script for adminer.

Thanks

### CODE REVIEW

**Comment by fmunozs** [comment]
Hello team, I want to include some additional details for this PR:

- I am sourcing the common.sh script from the google fingerprinters folder, to avoid having an additional copy.
- Docker and git are required and the official repo and docker images are used to do the fingerprinting.
- This PR updates the adminer.binproto file included on google fingerprinters plugin.

Thanks!

**Comment by maoning** [comment]
@fmunozs yes, please! I've restructured the folders such that the common toolings are available to all the fingerprints.

**Comment by maoning** [comment]
Could you do the following: 

1. create https://github.com/google/tsunami-security-scanner-plugins/tree/master/google/fingerprinters/web/src/main/resources/fingerprinters/web/data/commuity folder and put your binary proto there.
2. create https://github.com/google/tsunami-security-scanner-plugins/tree/master/google/fingerprinters/web/scripts/updater/community folder and put your updater script there.

**Comment by fmunozs** [comment]
Hello, 

I just updated the PR with your recommendations! Just one thing, up to you to decide if you want me to drop the adminer.binproto that is included by google.

Thanks again!

**Pull request merged**
