### PR TITLE
Exposed spark api payload

### PR DESCRIPTION
**Pull request by timoles**
Exposed Spark API payload for #449

### CODE REVIEW

**Comment by maoning** [comment]
@timoles the code mirroring flagged the binary file, could you remove it from your PR (the file deletion isn't available to me for some reason). I will generate the .jar file on my side and commit it.

**Comment by timoles** [comment]
> @timoles the code mirroring flagged the binary file, could you remove it from your PR (the file deletion isn't available to me for some reason). I will generate the .jar file on my side and commit it.

Done :)

**Comment by maoning** [comment]
> > @timoles the code mirroring flagged the binary file, could you remove it from your PR (the file deletion isn't available to me for some reason). I will generate the .jar file on my side and commit it.
> 
> Done :)

The github user you used for the PR update is different from the original one. You may need to sign the CLA again with the new user.

**Comment by maoning** [comment]
@timoles let me know if you can update the PR to unblock the merge :)

**Comment by timoles** [comment]
@maoning , sorry for the delay. I just updated the CLA

**Pull request merged**
