### PR TITLE
AI PRP: Request New Web Fingerprint for Kubeflow Model UI #422 

### PR DESCRIPTION
**Pull request by hayageek**
Hi @maoning, @tooryx,
This PR is linked to an accepted AI PRP: Request New Web Fingerprint for Kubeflow Model UI #422 . It covers versions `0.7.0` to `0.10.0`

I have tested the changes with the scanner.
Please find the attached screenshots for the scan log & json output.

kubeflow-json-output
kubeflow-log

### CODE REVIEW

**Comment by hayageek** [comment]
Hi @tooryx ,
Can you verify and merge the pull requests

**Comment by hayageek** [comment]
Hi @leonardo-doyensec , 
I have added `v0.13.0-rc.0`, and tested the scanner. I have attached the screenshot for your reference.
Screenshot 2024-07-12 at 9 01 26 PM
Screenshot 2024-07-12 at 9 02 03 PM

**Comment by hayageek** [comment]
@leonardo-doyensec  any update ?

**Comment by hayageek** [comment]
@leonardo-doyensec  any update ?

**Comment by hayageek** [comment]
Hi @leonardo-doyensec ,
Are you waiting for one more version by Kubeflow ?

**Comment by leonardo-doyensec** [comment]
**LGTM** - Approved
@maoning you can merge it.

_Reviewer_: Leonardo, Doyensec
_Plugin_: Kubeflow Model UI Fingerprints
_Feedback_: Besides the version.txt file being initially incomplete, due to time delays, the script worked first try and the quality is good.
_Drawbacks_: None

**Review by tooryx — APPROVED** [review]
Thank you @hayageek. This should be merged soon.

**Pull request merged**
